language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  # Install miniconda (makes for easier scipy installation)
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # set up environment and python dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda install -n test-environment numpy scipy sphinx
  - conda install -n test-environment pytest pytest-cov
  - conda install -n test-environment pylint
  - source activate test-environment
  - pip install coveralls
# command to run tests
script: 
  - python setup.py develop && py.test --cov=klpysci
  - pylint --rcfile=pylintrc klpysci
after_success:
  - coveralls

